apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapp-gateway
spec:
  selector:
    matchLabels:
      app: yapp-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: yapp-gateway
    spec:
      containers:
      - name: yapp-gateway
        image: igorperikov/yapp-gateway:latest
        env:
        - name: MESSAGING_URI
          value: http://yapp-messaging-service:8081
        - name: AUTH_URI
          value: http://yapp-auth-service:8083
        - name: INTEGRATION_URI
          value: http://yapp-integration-service:8082
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: yapp-gateway-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: yapp-gateway
  type: NodePort
