apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapp-integration
spec:
  selector:
    matchLabels:
      app: yapp-integration
  replicas: 1
  template:
    metadata:
      labels:
        app: yapp-integration
    spec:
      containers:
      - name: yapp-integration
        image: igorperikov/yapp-integration:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: yapp-integration-service
spec:
  ports:
  - port: 80
    targetPort: 8082
  selector:
    app: yapp-integration
  type: NodePort
