apiVersion: apps/v1
kind: Deployment
metadata:
  name: yapp-messaging
spec:
  selector:
    matchLabels:
      app: yapp-messaging
  replicas: 1
  template:
    metadata:
      labels:
        app: yapp-messaging
    spec:
      containers:
      - name: yapp-messaging
        env:
        - name: JDBC_URL
          value: jdbc:postgresql://pg-service:5432/postgres?user=my_yapp_user&password=my_yapp_password&ssl=false
        image: igorperikov/yapp-messaging:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: yapp-messaging-service
spec:
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: yapp-messaging
  type: NodePort
