apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  ports:
  - port: 5432
  selector:
    app: pg
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: pg
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - image: postgres:10.3
        name: postgres
        env:
        - name: POSTGRES_USER
          value: my_yapp_user
        - name: POSTGRES_PASSWORD
          value: my_yapp_password
        ports:
        - containerPort: 5432
          name: pg
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim
